---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: calico-accountant
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: calico-accountant
  template:
    metadata:
      labels:
        app: calico-accountant
    spec:
      serviceAccountName: calico-accountant
      containers:
        - command:
           - "/calico-accountant"
           - "-logtostderr=true"
           - "-v=2"
          env:
          - name: DATASTORE_TYPE
            value: "kubernetes"
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: METRICS_SERVER_PORT
            value: "9009"
          image: ghcr.io/fredrikcarlssn/calico-accountant-v3.29:latest 
          name: calico-accountant
          securityContext:
            privileged: true
      hostNetwork: true
